// Generates a lookup table and a cfg for lib.rs.
use std::fmt::Write;

fn main() {
    let mut out = String::from("/// Generated by build.rs.\npub const PRIMES: [u32; 12] = [");
    let mut found = 0;
    let mut n = 2u32;
    while found < 12 {
        if (2..n).all(|d| n % d != 0) {
            write!(out, "{n}, ").unwrap();
            found += 1;
        }
        n += 1;
    }
    out.push_str("];\npub const GENERATED_NAME: &str = \"sink\";\n");
    let dir = std::env::var("OUT_DIR").unwrap();
    std::fs::write(format!("{dir}/generated.rs"), out).unwrap();
    println!("cargo::rustc-check-cfg=cfg(sink_generated)");
    println!("cargo::rustc-cfg=sink_generated");
    println!("cargo::rerun-if-changed=build.rs");
}
