[workspace]
members = ["macros", "core", "mid", "dy", "nightly", "old"]

[package]
name = "sink"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
sink-core = { path = "core" }
sink-mid = { path = "mid" }
sink-macros = { path = "macros" }
sink-dy = { path = "dy" }
sink-nightly = { path = "nightly" }
sink-old = { path = "old" }
