[workspace]
resolver = "3"
members = [
    "crates/mirth",
    "crates/mirth-build",
    "crates/mirth-cli",
    "crates/mirth-runtime",
    "crates/mirth-watch",
    "crates/mirth-rewrite",
    "crates/mirth-lab",
    "examples/count-calls",
]
exclude = ["fixtures"]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false
